### PR TITLE
Bugfix/elineb/fix plot grids

### PR DESCRIPTION
**Pull request by kathrynline**

### CODE REVIEW

**Comment by kathrynline** [comment]
This seemed to make the plots look marginally better - examples before and after here. 
[global_after.pdf](https://github.com/ihmeuw/covid-model-infections/files/6305072/global_after.pdf)
[global_before.pdf](https://github.com/ihmeuw/covid-model-infections/files/6305073/global_before.pdf)

**Comment by rmbarber** [comment]
were these produced by a Jenkins run? the issue is that in the overnight runs the plots come out extra squished, more than in your global_before plot - see example:
image

**Review by collijk — APPROVED** [review]

**Comment by kathrynline** [comment]
Yes @rmbarber , these plots did come from a Jenkins run.

**Comment by rmbarber** [comment]
wonderful

**Review by rmbarber — APPROVED** [review]

**Pull request merged**
